services:
  inventory-service:
    build:
      context: ./services/inventory
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3031
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "3031:3031"

  order-service:
    build:
      context: ./services/order
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3032
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "3032:3032"

  payment-service:
    build:
      context: ./services/payment
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3033
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "3033:3033"

  product-service:
    build:
      context: ./services/product
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3034
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "3034:3034"

  user-service:
    build:
      context: ./services/user
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3035
      - MONGO_URI=${MONGO_URI}
      - RABBITMQ_URL=${RABBITMQ_URL}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - "3035:3035"

  email-service:
    build:
      context: ./services/email
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3036
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - RABBITMQ_URL=${RABBITMQ_URL}
    ports:
      - "3036:3036"
    depends_on:
      - order-service
      - payment-service

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - inventory-service
      - order-service
      - product-service
      - user-service
      - payment-service
      - email-service