name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests and Publish Results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Copy shared directory to services
        run: bash scripts/copyShared.sh

      - name: Install dependencies for all services
        run: |
          cd services/inventory && npm install && cd -
          cd services/order && npm install && cd -
          cd services/payment && npm install && cd -
          cd services/product && npm install && cd -
          cd services/user && npm install && cd -

      - name: Run All Unit Tests
        run: |
          npx jest \
            "services/inventory/tests/**/*.test.js" \
            "services/order/tests/**/*.test.js" \
            "services/payment/tests/**/*.test.js" \
            "services/product/tests/**/*.test.js" \
            "services/user/tests/**/*.test.js" \
            --reporters=default \
            --reporters=jest-junit \
            --outputFile=junit.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: |
            junit.xml
