name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests and Publish Results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Copy shared directory to services
        run: bash scripts/copyShared.sh

      # Inventory Service
      - name: Install dependencies for Inventory Service
        working-directory: ./services/inventory
        run: npm install

      - name: Run Unit Tests for Inventory Service
        working-directory: ./services/inventory
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Publish Test Results for Inventory Service
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: ./services/inventory/junit.xml

      - name: Upload Coverage for Inventory Service
        uses: actions/upload-artifact@v3
        with:
          name: inventory-coverage-report
          path: ./services/inventory/coverage/

      # Order Service
      - name: Install dependencies for Order Service
        working-directory: ./services/order
        run: npm install

      - name: Run Unit Tests for Order Service
        working-directory: ./services/order
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Publish Test Results for Order Service
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: ./services/order/junit.xml

      - name: Upload Coverage for Order Service
        uses: actions/upload-artifact@v3
        with:
          name: order-coverage-report
          path: ./services/order/coverage/

      # Payment Service
      - name: Install dependencies for Payment Service
        working-directory: ./services/payment
        run: npm install

      - name: Run Unit Tests for Payment Service
        working-directory: ./services/payment
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Publish Test Results for Payment Service
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: ./services/payment/junit.xml

      - name: Upload Coverage for Payment Service
        uses: actions/upload-artifact@v3
        with:
          name: payment-coverage-report
          path: ./services/payment/coverage/

      # Product Service
      - name: Install dependencies for Product Service
        working-directory: ./services/product
        run: npm install

      - name: Run Unit Tests for Product Service
        working-directory: ./services/product
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Publish Test Results for Product Service
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: ./services/product/junit.xml

      - name: Upload Coverage for Product Service
        uses: actions/upload-artifact@v3
        with:
          name: product-coverage-report
          path: ./services/product/coverage/

      # User Service
      - name: Install dependencies for User Service
        working-directory: ./services/user
        run: npm install

      - name: Run Unit Tests for User Service
        working-directory: ./services/user
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Publish Test Results for User Service
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: always()
        with:
          files: ./services/user/junit.xml

      - name: Upload Coverage for User Service
        uses: actions/upload-artifact@v3
        with:
          name: user-coverage-report
          path: ./services/user/coverage/