name: Run Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests and Publish Results
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Copy shared directory to services
        run: bash scripts/copyShared.sh

      - name: Install dependencies for Inventory Service
        working-directory: ./services/inventory
        run: npm install

      - name: Run Unit Tests for Inventory Service
        working-directory: ./services/inventory
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Install dependencies for Order Service
        working-directory: ./services/order
        run: npm install

      - name: Run Unit Tests for Order Service
        working-directory: ./services/order
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Install dependencies for Payment Service
        working-directory: ./services/payment
        run: npm install

      - name: Run Unit Tests for Payment Service
        working-directory: ./services/payment
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Install dependencies for Product Service
        working-directory: ./services/product
        run: npm install

      - name: Run Unit Tests for Product Service
        working-directory: ./services/product
        run: npm test -- --reporters=default --reporters=jest-junit

      - name: Install dependencies for User Service
        working-directory: ./services/user
        run: npm install

      - name: Run Unit Tests for User Service
        working-directory: ./services/user
        run: npm test -- --reporters=default --reporters=jest-junit